### ISSUE TITLE
Destroy main page Dokuwiki

### ISSUE THREAD

**Issue by saulocorbellari** [TheSkorm/dokuipmap#6]
Instalation by extension manager, destroy main page. 

PHP error:
cat /var/log/apache2/error.log

 PHP Fatal error:  Declaration of syntax_plugin_ipmap_rendertables::handle() must be compatible with dokuwiki\\Extension\\SyntaxPlugin::handle($match, $state, $pos, Doku_Handler $handler) in /var/www/dokuwiki/lib/plugins/ipmap/syntax/rendertables.php on line 0

Temporary solution:

sudo rm -Rf /var/www/dokuwiki/lib/plugins/ipmap/

**Comment by TheSkorm** [comment]
hey sorry, This plugin hasn't been looked at in over 10 years. It's highly likely it doesn't work with any modern version of dokuwiki

**Comment by TheSkorm** [comment]
It's also like that it won't work on modern 64bit systems because of this issue : #4

**Comment by TheSkorm** [comment]
Hi @saulocorbellari I rolled back to an older version where #4 is fixed. I've also made the changes required to get it to work on modern dokuwiki. Hopefully it works for you now :)
